### ISSUE TITLE
Name for the project

### ISSUE THREAD

**Issue by icaropires** [fga-eps-mds/2019.1-simulador-de-frenagem#5]
"Simulador de Frenagem" is not a good name for a project. What you, guys, suggest?

**Comment by icaropires** [comment]
UnBreak?

**Comment by joaorobson** [comment]
UnBrake

**Comment by icaropires** [comment]
> UnBrake

Yes! I wrote wrong.

**Comment by joaorobson** [comment]
Unbrake in English means stop braking too. In other words, accelerate. It seems a good name

**Comment by Bumbleblo** [comment]
UnBrake... it's funny and a liked

**Comment by icaropires** [comment]
As most of contributors (@joaorobson, @icaropires, @Bumbleblo, @GabrielTiveron and @ViniciusBernardo) manifested favorable. It's decided!
